### ISSUE TITLE
Symfony error while trying to install the plugin

### ISSUE THREAD

**Issue by milosrusov** [gugacavalieri/mautic-sentEmail-webhook#1]
Hello, 
I was trying to install this plugin but it wass not successful.
This is the erorr that I am getting when I try to clear the cache: 

[Symfony\Component\Debug\Exception\FatalErrorException]                                                               
  Compile Error: Cannot declare class MauticPlugin\EmailSentBundle\EmailSentBundle, because the name is already in use.

Can you please advise what can I do to solve this issue?
I am using version 2.14.2.

 Thanks in advance!

**Comment by gugacavalieri** [comment]
looking into it ...

**Comment by gugacavalieri** [comment]
Fixed in v1.0.1
https://github.com/gugacavalieri/MauticEmailSentNotifierBundle/releases

# Update:
Make sure the folder is named MauticEmailSentNotifierBundle *(same name as MauticEmailSentNotifierBundle.php)* . Otherwise you will get an namespace error when trying to clear the cache
