### ISSUE TITLE
Bug during renaming.

### ISSUE THREAD

**Issue by Techmind** [gugacavalieri/mautic-sentEmail-webhook#2]
```
public static function getIntegration()
    {
        try {
            return self::$integratonHelper->getIntegrationObject('EmailSent');
        } catch (\Exception $e) {
            // do nothing
        }
        return null;
    }
```
Should be "EmailSentNotifier" after renaming. Does not work currently.

**Comment by gugacavalieri** [comment]
Fixed with #3 ! Marking this as closed

Thanks for the heads up :)

Also, just released a new version
(https://github.com/gugacavalieri/MauticEmailSentNotifierBundle/releases/tag/v1.0.2)
