### ISSUE TITLE
"Integration" is misspelled as "Integraton" several times in the Helper class

### ISSUE THREAD

**Issue by StoppingBuck** [gugacavalieri/mautic-sentEmail-webhook#4]
e.g. as "integratonHelper". I don't know if it affects functionality as I'm still debugging how to get the plugin to work.

**Comment by gugacavalieri** [comment]
Since it's just a private variable I don't think it is a big deal.

But I am opening a new PR to fix it.

Second, what are you struggling with to get it to work ?

**Comment by StoppingBuck** [comment]
@gugacavalieri For some weird reason, every webhook is sent twice.

For example, if I send out a segment email to a segment consisting of 3 people, my backend receives 6 calls from this webhook in total: 2 for each person in the segment.

I'm currently in the process of figuring out why/how that happens...

**Comment by gugacavalieri** [comment]
That's weird. I don't remember that happening to me ... 

Have you found anything yet? 

If you find anything just let me know, I will be glad to help :)

**Comment by gugacavalieri** [comment]
I will close this thread since this issue has been resolved.

It might be good to open another issue to discuss why the plugin is sending the request twice
